/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

uint32_t time=10000;

int main(void)
{
	uint32_t *pClkCtrlReg =   (uint32_t*)0x40021018;  //PORT C Clock adress
	uint32_t *pPortCModeReg = (uint32_t*)0x40011004; //PORT C Mode adress
	uint32_t *pPortCOutReg =  (uint32_t*)0x4001100C; //PORT C ODR  adress

	//1. enable the clock for GPOIC peripheral in the APB2ENR (SET the 4th bit position)
	*pClkCtrlReg |= ( 1 << 4);

	//2. configure the mode of the IO pin as output and speed // In memory map, default is 0100
	//   make 0th bit position as 1 (SET)

	*pPortCModeReg |= ( 3 << 0); // (GPIOx_CRH)
	*pPortCModeReg &= ~( 3 << 2);


	//SET 8th bit of the output data register to make I/O pin-8 as HIGH
	*pPortCOutReg |= ( 1 << 8);


    while(1);
}
