/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f1xx.h"

void gpioConfig(){

	GPIO_Handle_t  pGPIOhandle;


	pGPIOhandle.pGPIOx = GPIOC;
	pGPIOhandle.GPIO_PinConfig.GPIO_Mode = GPIO_MODE_OUT_PP;
	pGPIOhandle.GPIO_PinConfig.GPIO_Pin = GPIO_Pin_10;
	pGPIOhandle.GPIO_PinConfig.GPIO_Speed = GPIO_SPEED_MEDIUM;

	GPIO_PCLK(GPIOC, ENABLE);

	GPIO_Init(&pGPIOhandle);

}

void delay(uint32_t time){

	while(time--);

}

int main(void)
{
	gpioConfig();

	while(1){

//		GPIO_WriteToOutputPin(GPIOC, GPIO_Pin_10,GPIO_PIN_SET);
//		delay(500000);
//		GPIO_WriteToOutputPin(GPIOC, GPIO_Pin_10,GPIO_PIN_RESET);
		GPIO_ToggleOutputPin(GPIOC, GPIO_Pin_10);
		delay(500000);

	}

}
